"""Init migration

Revision ID: 57dfc468b744
Revises: 
Create Date: 2026-09-25 15:01:30.435205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57dfc468b744'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objecttype',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructureobject',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('base_life_years', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('object_type', sa.Integer(), nullable=False),
    sa.Column('section', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_type'], ['objecttype.id'], name='fk_infrastructureobject_objecttype_id_objecttype'),
    sa.ForeignKeyConstraint(['section'], ['section.id'], name='fk_infrastructureobject_section_id_section'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hardware_infrastructureobject',
    sa.Column('hardware_id', sa.Integer(), nullable=False),
    sa.Column('infrastructureobject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], ),
    sa.ForeignKeyConstraint(['infrastructureobject_id'], ['infrastructureobject.id'], ),
    sa.PrimaryKeyConstraint('hardware_id', 'infrastructureobject_id')
    )
    op.create_table('material_infrastructureobject',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('infrastructureobject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['infrastructureobject_id'], ['infrastructureobject.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('material_id', 'infrastructureobject_id')
    )
    op.create_table('wearrecord',
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=False),
    sa.Column('total_wear_pct', sa.Float(), nullable=False),
    sa.Column('base_wear_pct', sa.Float(), nullable=False),
    sa.Column('extra_wear_pct', sa.Float(), nullable=False),
    sa.Column('annual_rate_pct', sa.Float(), nullable=False),
    sa.Column('remaining_years', sa.Integer(), nullable=False),
    sa.Column('factor_freeze_thaw', sa.Float(), nullable=False),
    sa.Column('factor_precip', sa.Float(), nullable=False),
    sa.Column('factor_wind', sa.Float(), nullable=False),
    sa.Column('factor_snow', sa.Float(), nullable=False),
    sa.Column('factor_heat', sa.Float(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['infrastructureobject.id'], name='fk_wearrecord_infrastructureobject_id_infrastructureobject'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wearrecord')
    op.drop_table('material_infrastructureobject')
    op.drop_table('hardware_infrastructureobject')
    op.drop_table('infrastructureobject')
    op.drop_table('section')
    op.drop_table('objecttype')
    op.drop_table('material')
    op.drop_table('hardware')
    # ### end Alembic commands ###
