"""Add infrastructure object model

Revision ID: be66897035e7
Revises: 441981cfdc46
Create Date: 2026-09-25 14:37:30.619192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be66897035e7'
down_revision: Union[str, None] = '441981cfdc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objecttype',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructureobject',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('base_life_years', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('object_type', sa.Integer(), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_type'], ['objecttype.id'], name='fk_infrastructureobject_objecttype_id_objecttype'),
    sa.ForeignKeyConstraint(['section'], ['section.id'], name='fk_infrastructureobject_section_id_section'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hardware_infrastructureobject',
    sa.Column('hardware_id', sa.Integer(), nullable=False),
    sa.Column('infrastructureobject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], ),
    sa.ForeignKeyConstraint(['infrastructureobject_id'], ['infrastructureobject.id'], ),
    sa.PrimaryKeyConstraint('hardware_id', 'infrastructureobject_id')
    )
    op.create_table('material_infrastructureobject',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('infrastructureobject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['infrastructureobject_id'], ['infrastructureobject.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('material_id', 'infrastructureobject_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_infrastructureobject')
    op.drop_table('hardware_infrastructureobject')
    op.drop_table('infrastructureobject')
    op.drop_table('section')
    op.drop_table('objecttype')
    op.drop_table('material')
    op.drop_table('hardware')
    # ### end Alembic commands ###
